# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messages.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\"\x87\x01\n\x11\x43onnectionRequest\x12%\n\x04type\x18\x01 \x01(\x0e\x32\x17.ConnectionRequest.Type\x12\x13\n\x0b\x63lient_name\x18\x02 \x01(\t\x12\x19\n\x11\x63lient_identifier\x18\x03 \x01(\x0c\"\x1b\n\x04Type\x12\x07\n\x03RPC\x10\x00\x12\n\n\x06STREAM\x10\x01\"c\n\x10TelemetryPayload\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0c\n\x04roll\x18\x02 \x01(\x02\x12\r\n\x05pitch\x18\x03 \x01(\x02\x12\x0b\n\x03yaw\x18\x04 \x01(\x02\x12\x15\n\rencoder_count\x18\x05 \x01(\x05\"\xa5\x01\n\x14RealTelemetryPayload\x12\x16\n\x0epacket_version\x18\x01 \x01(\r\x12\x10\n\x08sequence\x18\x02 \x01(\r\x12\x13\n\x0bstatus_mask\x18\x03 \x01(\r\x12\x10\n\x08yaw_cdeg\x18\x04 \x01(\x0f\x12\x12\n\npitch_cdeg\x18\x05 \x01(\x0f\x12\x11\n\troll_cdeg\x18\x06 \x01(\x0f\x12\x15\n\rencoder_ticks\x18\x07 \x01(\x0f\x62\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONNECTIONREQUEST']._serialized_start=19
  _globals['_CONNECTIONREQUEST']._serialized_end=154
  _globals['_CONNECTIONREQUEST_TYPE']._serialized_start=127
  _globals['_CONNECTIONREQUEST_TYPE']._serialized_end=154
  _globals['_TELEMETRYPAYLOAD']._serialized_start=156
  _globals['_TELEMETRYPAYLOAD']._serialized_end=255
  _globals['_REALTELEMETRYPAYLOAD']._serialized_start=258
  _globals['_REALTELEMETRYPAYLOAD']._serialized_end=423
# @@protoc_insertion_point(module_scope)
